
# Generated by Django 5.1.4 on 2024-12-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenseName',
            field=models.CharField(default='item', max_length=100),
        ),
    ]
