# Generated by Django 5.1.4 on 2024-12-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_expense_expensename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
