# Generated by Django 5.1.4 on 2024-12-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_expenseshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0.0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_receiver', to='myapp.person')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_payer', to='myapp.person')),
            ],
        ),
    ]
