# Generated by Django 5.1.4 on 2025-01-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_balance_settletran'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='rPerson',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='receive_person', to='myapp.person'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owing_person', to='myapp.person'),
        ),
    ]
