# Generated by Django 5.1.4 on 2025-01-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_balance_rperson_alter_balance_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseshare',
            name='splitType',
            field=models.CharField(default='equal', max_length=50),
        ),
    ]
