# Generated by Django 5.1.4 on 2025-01-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_expenseshare_splittype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseshare',
            name='splitType',
            field=models.CharField(choices=[(1, 'equal'), (3, 'percent'), (2, 'unequal')], max_length=50),
        ),
    ]
