# Generated by Django 5.1.4 on 2025-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_expenseshare_splittype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseshare',
            name='splitType',
            field=models.CharField(default='equal', max_length=50),
        ),
    ]
